export const APPSETTINGS_SET_THEME = 'APPSETTINGS_SET_THEME';
export const APPSETTINGS_SET_LANGUAGE = 'APPSETTINGS_SET_LANGUAGE';
export const HOMEACTIONS_SET_LIST_TYPE = 'HOMEACTIONS_SET_LIST_TYPE';
export const HOMEACTIONS_SET_RESTAURANTS = 'HOMEACTIONS_SET_RESTAURANTS';
export const HOMEACTIONS_SET_PROCESSING = 'HOMEACTIONS_SET_PROCESSING';
